version: '3'

services:
  # PostgreSQL Database Service
  postgresql:
    container_name: ms_pg_sql
    image: postgres:16
    environment:
      POSTGRES_USER: haifawi              # Username for PostgreSQL
      POSTGRES_PASSWORD: haifawi          # Password for PostgreSQL
      PGDATA: /data/postgres             # Location to store data
    volumes:
      - postgres:/data/postgres          # Persist data outside the container
    ports:
      - "5432:5432"                      # Expose DB on localhost:5432
    networks:
      - microservices-net
    restart: unless-stopped

  # PostgreSQL Admin UI (pgAdmin)
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}        # Admin email (can override)
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}                 # Admin password (can override)
      PGADMIN_CONFIG_SERVER_MODE: 'False'                                         # Set pgAdmin to desktop mode
    volumes:
      - pgadmin:/var/lib/pgadmin                # Persist pgAdmin data
    ports:
      - "5050:80"                               # Host 5050 maps to container 80
    networks:
      - microservices-net
    restart: unless-stopped

  # Distributed tracing for microservices
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"           # Zipkin runs its UI and API on 9411
    networks:
      - microservices-net

  # MongoDB Database
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017           # Default MongoDB port
    volumes:
      - mongo:/data           # Persist database data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=haifawi    # Mongo root username
      - MONGO_INITDB_ROOT_PASSWORD=haifawi    # Mongo root password

  # MongoDB Administration UI
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=haifawi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=haifawi
      - ME_CONFIG_MONGODB_SERVER=mongodb      # Hostname of the mongo service

  # Apache ZooKeeper - needed for Kafka broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  # Apache Kafka - message broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ms_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # host:9092 -> PLAINTEXT_HOST listener
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Two listeners:
      # - PLAINTEXT: used INSIDE docker network by other containers (ms_kafka:29092)
      # - PLAINTEXT_HOST: used from your laptop (localhost:9092)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ms_kafka:29092,PLAINTEXT_HOST://localhost:9092

      # Single-broker cluster settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - microservices-net


      # MailDev - fake SMTP server for development/testing emails
  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080     # Web UI for viewing emails
      - 1025:1025     # SMTP port to send emails from apps

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9098:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge    # Isolated network for microservices

volumes:
  postgres:           # PostgreSQL data
  pgadmin:            # pgAdmin configuration
  mongo:              # MongoDB data
